name: Auto Version & Publish

on:
  push:
    branches:
      - master
      - main

jobs:
  version-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Determine version bump type
        id: bump-type
        run: |
          # Default to patch
          VERSION_TYPE="patch"
          
          # Check if this is a merge commit
          if [ "$(git rev-list --merges -n 1 HEAD)" == "$(git rev-parse HEAD)" ]; then
            # Get PR number from merge commit
            PR_NUMBER=$(git log -1 --pretty=%B | grep -oP '#\K\d+' | head -1)
            
            if [ ! -z "$PR_NUMBER" ]; then
              # Check PR labels using GitHub API
              LABELS=$(curl -s \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
                | jq -r '.labels[].name' | tr '\n' ' ')
              
              if [[ "$LABELS" == *"major"* ]]; then
                VERSION_TYPE="major"
              elif [[ "$LABELS" == *"minor"* ]]; then
                VERSION_TYPE="minor"
              elif [[ "$LABELS" == *"patch"* ]]; then
                VERSION_TYPE="patch"
              fi
            fi
          fi
          
          # Fallback to commit message parsing
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" == *"BREAKING CHANGE"* ]] || [[ "$COMMIT_MSG" == *"!"* ]]; then
            VERSION_TYPE="major"
          elif [[ "$COMMIT_MSG" == *"feat:"* ]] || [[ "$COMMIT_MSG" == *"feat("* ]]; then
            VERSION_TYPE="minor"
          fi
          
          echo "type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "Determined version bump type: $VERSION_TYPE"

      - name: Check current version
        id: check-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Bump version
        id: version-bump
        run: |
          npm version ${{ steps.bump-type.outputs.type }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped from ${{ steps.check-version.outputs.current_version }} to $NEW_VERSION"

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
        continue-on-error: true  # Remove this line once you have tests

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore: release v${{ steps.version-bump.outputs.new_version }} [skip ci]"
          git tag v${{ steps.version-bump.outputs.new_version }}

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.ref_name }}
          git push origin v${{ steps.version-bump.outputs.new_version }}

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-bump.outputs.new_version }}
          release_name: Release v${{ steps.version-bump.outputs.new_version }}
          body: |
            ## What's Changed
            
            Version bump type: ${{ steps.bump-type.outputs.type }}
            Previous version: ${{ steps.check-version.outputs.current_version }}
            New version: ${{ steps.version-bump.outputs.new_version }}
            
            See [commit history](https://github.com/${{ github.repository }}/compare/v${{ steps.check-version.outputs.current_version }}...v${{ steps.version-bump.outputs.new_version }}) for details.
          draft: false
          prerelease: false
