name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$VERSION" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to v${{ env.new_version }}"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version to v${{ env.new_version }}"
          title: "chore: bump version to v${{ env.new_version }}"
          body: |
            This PR bumps the version to v${{ env.new_version }}.
            
            Type: ${{ github.event.inputs.version_type }}
            
            After merging this PR, the package will be automatically published to npm.
          branch: version-bump-${{ env.new_version }}
          delete-branch: true